"""Add index in SpimexTradingResults

Revision ID: 72e7725c3bec
Revises: 2a323f20704b
Create Date: 2025-03-26 07:01:58.848081

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72e7725c3bec'
down_revision: Union[str, None] = '2a323f20704b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_spimex_trading_results_date'), 'spimex_trading_results', ['date'], unique=False)
    op.create_index(op.f('ix_spimex_trading_results_delivery_basis_id'), 'spimex_trading_results', ['delivery_basis_id'], unique=False)
    op.create_index(op.f('ix_spimex_trading_results_delivery_type_id'), 'spimex_trading_results', ['delivery_type_id'], unique=False)
    op.create_index(op.f('ix_spimex_trading_results_oil_id'), 'spimex_trading_results', ['oil_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_spimex_trading_results_oil_id'), table_name='spimex_trading_results')
    op.drop_index(op.f('ix_spimex_trading_results_delivery_type_id'), table_name='spimex_trading_results')
    op.drop_index(op.f('ix_spimex_trading_results_delivery_basis_id'), table_name='spimex_trading_results')
    op.drop_index(op.f('ix_spimex_trading_results_date'), table_name='spimex_trading_results')
    # ### end Alembic commands ###
